import numpy as np

matrix_for_converter1 = np.array([[True, True, True, True, True, True]])


matrix_for_converter2 = np.array([[True, True, False, False, False, False, False, True, False, False, True, False, False, False, True,],
                                  [True, False, True, False, False, False, False, True, False, False, True, True, False, False, True,],
                                  [True, False, False, True, False, False, False, False, True, False, True, True, True, False, True,],
                                  [True, False, False, False, True, False, False, False, True, False, False, True, True, True, True,],
                                  [True, False, False, False, False, True, False, False, False, True, False, False, True, True, True,],
                                  [True, False, False, False, False, False, True, False, False, True, False, False, False, True, True,]])


matrix_for_converter3 = np.array(  [[True, False, False, False, False, False, True, True, True, True, False, False, True, False, True, True, False, False, True, True, False, True, True, True, False, False, False, False, True, True],
                                    [False, False, True, True, False, True, True, True, True, False, True, True, False, False, True, True, False, False, False, True, False, True, True, True, True, True, True, False, True, False],
                                    [True, True, False, False, False, False, False, False, True, False, True, True, False, False, True, True, True, True, True, False, True, False, True, False, False, True, True, True, True, True],
                                    [False, True, True, False, False, False, False, False, True, True, False, False, True, True, True, True, True, True, False, False, False, True, False, True, True, True, False, True, True, False],
                                    [False, False, True, False, False, True, False, False, True, False, False, True, False, False, False, True, False, False, True, False, False, True, False, True, False, False, False, False, False, False],
                                    [False, True, False, False, False, True, True, False, False, False, True, True, True, False, True, False, False, False, True, False, True, True, False, False, True, True, False, True, False, True],
                                    [True, False, True, True, False, True, True, True, False, False, False, False, False, True, False, True, False, True, True, True, True, True, False, False, True, False, False, True, False, False],
                                    [False, False, True, True, True, False, False, False, True, True, False, True, False, False, True, False, False, True, False, True, False, False, False, True, True, False, False, True, False, True],
                                    [True, True, True, False, False, True, True, True, True, True, True, False, True, False, False, False, False, True, False, True, True, True, False, True, False, False, False, False, False, False],
                                    [True, False, True, True, False, True, False, True, True, False, False, True, False, True, True, False, True, False, True, False, True, True, False, True, True, True, False, True, True, True],
                                    [False, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False, False, False, False, True, False, False, False, True, False, False, True, False, False, True],
                                    [True, False, True, False, True, False, False, True, False, True, False, False, True, False, True, True, False, False, False, True, True, False, False, True, True, False, True, False, False, False],
                                    [False, True, True, True, False, False, True, True, True, True, True, True, True, False, False, False, False, True, False, True, True, False, False, True, False, False, True, True, True, True],
                                    [True, True, True, True, False, True, False, False, False, False, True, True, True, True, True, False, False, True, False, True, True, False, False, False, True, True, False, False, True, False],
                                    [True, False, True, True, False, True, False, False, False, True, True, False, False, True, True, True, False, False, True, True, False, True, False, True, True, False, True, True, False, True]])


matrix_for_converter4 = np.array(  [[True, False, False, False, True, True, True, True, False, False, True, False, True, True, True, False, True, False, False, True, False, True, False, True, True, False, False, True, False, False, True, True, False, False, False, True, False, True, True, False, True, False, True, False, True, True, False, True, False, True, False, True, False, False, True, False, True, True, True, False],
                                    [False, False, True, True, True, True, False, False, False, True, False, True, False, True, True, False, True, False, False, True, False, True, True, True, True, False, True, False, False, True, True, True, True, True, True, False, False, True, True, False, False, False, True, False, False, False, True, False, False, True, True, False, False, False, True, False, False, True, True, True],
                                    [True, False, False, True, True, False, False, False, False, False, False, False, True, True, False, True, False, False, True, True, True, False, True, False, True, False, True, True, True, False, True, False, False, False, False, True, True, True, True, False, False, True, False, True, True, True, True, False, True, True, False, False, False, False, False, False, True, False, True, True],
                                    [False, True, True, False, True, True, False, True, True, True, False, True, False, True, False, False, True, True, True, True, False, False, True, False, True, False, True, False, True, False, False, False, False, True, False, False, False, False, False, True, True, True, False, True, True, True, False, True, True, True, False, False, False, False, True, True, True, True, False, False],
                                    [True, True, False, True, True, True, True, False, False, False, True, True, False, True, False, True, True, True, False, False, True, False, True, False, False, True, True, True, False, False, False, True, False, False, False, False, False, False, True, False, True, True, True, True, True, True, True, False, True, True, False, False, True, True, True, True, True, False, True, True],
                                    [True, True, True, False, False, True, True, True, False, True, True, True, True, True, False, True, True, True, True, False, False, False, False, False, False, True, True, True, False, False, True, False, False, False, False, False, True, True, True, True, True, False, True, False, True, True, False, True, True, False, False, False, False, True, True, False, False, True, False, False],
                                    [True, True, True, False, True, True, True, False, False, True, False, False, True, False, False, False, True, True, True, False, False, True, False, True, False, True, True, True, False, False, False, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, False, True, False, False, True, True, False, True, True, True, False, True, True],
                                    [False, False, True, True, True, False, True, True, False, True, False, True, True, False, False, True, True, False, True, False, True, True, False, False, True, False, False, False, False, True, True, False, True, True, True, False, True, False, True, True, True, True, True, True, True, True, True, True, False, False, True, False, False, False, False, True, False, True, True, False],
                                    [False, False, False, False, True, False, False, True, True, True, False, True, False, False, False, False, False, True, False, True, True, True, False, True, True, False, True, False, False, True, False, False, True, True, True, False, False, True, True, True, True, True, True, False, True, False, True, False, True, True, True, True, False, True, False, True, True, False, False, False],
                                    [True, True, False, False, False, False, True, True, True, True, False, False, True, True, False, True, True, True, True, False, False, False, True, True, True, True, True, True, True, False, True, False, False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, True, False, False, True, False, False, True, True, True, True, True, False],
                                    [False, False, False, True, True, True, False, True, True, True, False, True, False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, True, True, False, True, False, True, True, False, True, True, False, False, False, True, True, False, True, False, True, True, False, True, True, True, False, False, False, True, False, False, False, False, False],
                                    [True, False, True, True, True, True, False, False, True, True, False, False, True, False, False, False, True, False, True, False, True, False, False, True, True, False, True, False, False, False, False, False, False, False, False, True, False, True, False, True, False, True, True, False, False, True, True, False, False, False, True, False, True, False, False, True, True, True, True, True],
                                    [False, True, False, False, False, True, True, False, True, True, False, False, False, True, False, False, True, False, False, False, True, True, True, False, False, False, True, False, False, False, False, True, True, True, False, True, True, True, True, False, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False, False, False, True, False],
                                    [False, False, True, True, True, True, False, True, True, True, True, True, True, False, False, False, True, True, False, True, False, True, False, True, False, False, True, True, True, True, False, False, True, False, False, True, True, True, True, False, False, False, False, True, True, True, True, False, True, False, False, False, False, False, False, False, False, True, True, False],
                                    [True, True, False, True, False, True, False, False, True, False, False, False, True, False, True, False, True, True, False, False, True, False, False, True, True, True, True, True, True, False, True, False, True, False, True, True, False, False, False, False, False, False, False, True, True, True, False, False, False, False, True, True, True, True, False, True, False, False, False, True],
                                    [False, False, True, False, True, False, False, False, True, False, False, False, True, True, True, True, False, False, False, False, False, True, False, False, False, True, False, True, False, True, False, True, True, True, True, False, True, True, False, True, False, False, True, False, True, True, False, False, False, True, False, False, False, True, False, True, False, True, False, False],
                                    [True, False, True, False, False, True, False, False, False, True, True, True, False, False, True, True, True, False, False, True, False, False, True, True, False, True, True, False, False, True, True, False, True, True, False, True, True, False, True, False, False, False, False, True, False, False, False, True, True, False, True, False, True, False, True, False, False, True, True, True],
                                    [True, True, True, True, False, False, True, False, True, False, False, False, True, False, True, False, True, False, False, True, True, False, False, True, False, False, True, False, False, True, True, False, True, False, False, False, False, True, True, True, False, True, True, False, False, False, False, True, False, True, False, True, False, False, False, False, False, True, False, True],
                                    [False, True, True, True, True, True, False, True, False, True, True, False, True, True, True, False, False, True, True, False, False, False, False, True, False, True, False, False, False, True, True, True, False, True, False, True, False, False, True, True, False, False, True, True, False, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False],
                                    [False, True, False, False, True, True, False, True, True, True, True, False, False, True, False, False, True, False, False, True, True, False, False, True, True, True, False, False, True, True, False, True, True, True, False, True, False, False, True, False, False, False, False, False, False, False, True, False, False, True, True, True, False, True, True, False, True, False, True, False],
                                    [True, False, False, True, True, False, False, True, True, False, True, False, False, True, False, False, True, False, True, True, True, False, False, False, False, False, False, False, False, False, True, True, False, False, True, False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, True, False, True, True, False, True, True, False, False, True],
                                    [False, False, True, True, True, False, False, True, True, True, False, False, False, True, True, False, True, True, False, True, True, False, True, False, True, True, True, True, False, False, False, False, False, True, False, False, True, True, False, False, False, False, False, True, False, False, True, True, False, True, True, True, False, True, False, False, False, False, True, False],
                                    [False, True, False, False, True, True, True, False, True, False, True, True, False, True, True, False, False, False, False, True, True, False, True, False, True, True, False, False, True, False, False, False, True, True, False, False, False, True, True, True, False, False, False, False, True, True, True, True, False, True, True, True, False, True, True, False, False, False, False, True],
                                    [True, True, True, False, True, True, True, False, False, False, False, True, False, True, True, False, True, False, False, False, False, False, True, True, True, False, False, True, False, True, False, True, True, False, True, True, True, True, True, True, False, False, True, True, False, False, True, False, False, True, False, True, True, False, False, True, False, False, True, True],
                                    [False, False, False, False, False, False, True, True, False, True, True, True, True, False, True, False, True, True, True, False, True, False, False, True, False, False, True, True, False, False, False, False, True, True, True, False, True, False, True, False, False, False, False, False, False, True, True, False, False, True, True, True, True, False, True, False, True, True, True, False],
                                    [True, True, False, True, True, True, True, False, False, True, False, True, False, True, True, False, False, False, False, True, False, False, True, False, False, False, False, True, True, True, True, True, True, True, True, True, False, False, False, False, True, False, False, False, True, False, True, True, False, False, True, True, False, True, True, False, False, False, True, False],
                                    [False, True, True, True, False, False, True, False, True, True, True, False, True, False, True, True, True, False, False, False, True, True, True, False, False, False, False, True, False, False, False, False, True, True, True, False, False, False, False, False, False, False, True, False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, True, False],
                                    [True, False, False, True, False, False, False, False, True, False, False, True, True, False, False, True, False, True, False, True, False, False, True, False, True, False, False, False, False, True, False, False, False, True, True, True, True, True, False, True, True, False, False, False, False, False, False, False, True, True, True, False, False, True, True, False, False, False, False, True],
                                    [True, True, False, False, False, False, True, True, True, False, False, True, True, False, True, False, True, False, True, False, False, True, False, True, True, True, True, False, False, False, True, False, False, True, True, False, False, True, True, True, True, False, True, True, True, True, True, True, False, True, True, True, True, True, True, False, True, False, True, False],
                                    [True, True, False, True, True, True, False, False, True, False, False, False, True, True, True, True, False, False, True, True, False, True, False, True, True, False, False, False, False, False, False, True, True, False, False, True, True, False, False, True, True, True, True, True, False, True, False, False, True, True, True, True, False, True, False, False, True, False, True, False]])